name: Build
on:
  push:
    branches: [ master ]
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Install Grunt CLI
        run: sudo npm i -g grunt-cli
      - uses: actions/checkout@v2
        with:
          repository: 'keeweb/keeweb'
      - name: Install npm modules
        run: npm ci
      - name: Grunt
        run: grunt
