name: Build
on:
  push:
    branches: [ master ]
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Install multipass
        run: |
          sudo adduser $USER sudo
          sudo snap install multipass --classic
          journalctl -u snap.multipass*
          multipass info --all
          multipass list
          multipass launch --name foo
          multipass list
      - uses: actions/checkout@v2
        with:
          repository: 'keeweb/keeweb'
          ref: 'develop'
      - name: Install npm modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Grunt
        run: grunt
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: web-dist
          path: dist
  linux:
    runs-on: ubuntu-latest
    needs:
      - web
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'keeweb/keeweb'
          ref: 'develop'
      - name: Install snapcraft
        run: sudo snap install snapcraft --classic
      - name: Install multipass
        run: sudo snap install multipass --classic
      - name: Install npm modules
        run: npm ci
      - name: Download atrifact
        uses: actions/download-artifact@v1
        with:
          name: web-dist
          path: dist
      - name: Grunt
        run: grunt desktop-linux
      - name: ls
        run: ls -l dist
