name: Build
on:
  push:
    branches: [ master ]
jobs:
  Install dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Grunt
      - run: npm i -g grunt-cli
#      - uses: actions/checkout@v2
#        with:
#          repository: 'keeweb/keeweb'
      - name: ls
        run: node -v -e 'broken'
