name: Build
on:
  push:
    branches: [ master ]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'keeweb/keeweb'
      - name: ls
        run: node -v
