name: Build
on:
  push:
    branches: [ master ]
#    tags: [ '*' ]
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Get current git ref
        id: git_ref
        #run: echo ::set-output name=ref::${GITHUB_REF/refs\/tags\//}
        run: echo ::set-output name=ref::1.13.0
      - uses: actions/checkout@v2
        with:
          repository: 'keeweb/keeweb'
          ref: 'develop'
      - name: Install npm modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Grunt
        run: grunt
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.html.zip
          path: dist
  darwin:
    runs-on: macos-latest
    needs:
      - web
    steps:
      - name: Get current git ref
        id: git_ref
        #run: echo ::set-output name=ref::${GITHUB_REF/refs\/tags\//}
        run: echo ::set-output name=ref::1.13.0
      - uses: actions/checkout@v2
        with:
          repository: 'keeweb/keeweb'
          ref: 'develop'
      - name: Download atrifact
        uses: actions/download-artifact@v1
        with:
          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.html.zip
          path: dist
      - name: Install npm modules
        run: |
          npm ci
          cd desktop
          npm ci
          cd ..
      - name: Install grunt
        run: sudo npm i -g grunt-cli
      - name: Write secrets
        env:
          CODESIGN: ${{ secrets.CODESIGN }}
          APPLE_DEPLOY_PASSWORD: ${{ secrets.APPLE_DEPLOY_PASSWORD }}
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
        run: |
          mkdir keys
          echo "$CODESIGN" > keys/codesign.json
          xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u "$APPLE_ID_USERNAME" -p "$APPLE_DEPLOY_PASSWORD"
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      - name: Grunt
        run: grunt desktop-darwin
      - name: Upload dmg artifact
        uses: actions/upload-artifact@v1
        with:
          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.mac.dmg
          path: dist/desktop/KeeWeb-${{ steps.git_ref.outputs.ref }}.mac.dmg
#  linux:
#    runs-on: ubuntu-latest
#    needs:
#      - web
#    steps:
#      - name: Get current git ref
#        id: git_ref
#        #run: echo ::set-output name=ref::${GITHUB_REF/refs\/tags\//}
#        run: echo ::set-output name=ref::1.13.0
#      - uses: actions/checkout@v2
#        with:
#          repository: 'keeweb/keeweb'
#          ref: 'develop'
#      - name: Download atrifact
#        uses: actions/download-artifact@v1
#        with:
#          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.html.zip
#          path: dist
#      - name: Write secrets
#        env:
#          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#          KEEWEB_SIGN: ${{ secrets.KEEWEB_SIGN }}
#        run: |
#          mkdir keys
#          echo "$PRIVATE_KEY" > keys/private-key.pem
#          echo "$KEEWEB_SIGN" > keys/keeweb-sign.json
#      - uses: ./.github/actions/linux-build
#      - name: Upload AppImage artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.AppImage
#          path: dist/desktop/KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.AppImage
#      - name: Upload snap artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.snap
#          path: dist/desktop/KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.snap
#      - name: Upload deb artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.x64.deb
#          path: dist/desktop/KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.x64.deb
#      - name: Upload zip artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.x64.zip
#          path: dist/desktop/KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.x64.zip
#      - name: Upload rpm artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.x86_64.rpm
#          path: dist/desktop/KeeWeb-${{ steps.git_ref.outputs.ref }}.linux.x86_64.rpm
#      - name: Upload update artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: UpdateDesktop.zip
#          path: dist/desktop/UpdateDesktop.zip
